// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    'category': String,
    'varients': [String],
    'prices': [{
      'small': Number,
      'medium': Number,
      'large': Number,
      _id: false,
    }],
    'description': String,
    'image': String,
    'name': String,
  }, {
    timestamps: false,
  });

  return mongoose.model('pizzas', schema, 'pizzas');
};
